name: Build LaTeX and Upload PDF

on:
  push:
    branches:
      - master
      - 'feature/*'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: resume.tex

      - name: Set Dropbox target path
        id: dropbox-path
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          if [[ "$BRANCH_NAME" == "master" ]]; then
            echo "TARGET_PATH=master.pdf" >> $GITHUB_ENV
          else
            echo "TARGET_PATH=feature.pdf" >> $GITHUB_ENV
          fi

      - name: Generate Dropbox access token
        id: dropbox-token
        run: |
          access_token=$(curl -s https://api.dropbox.com/oauth2/token \
            -d grant_type=refresh_token \
            -d refresh_token="${{ secrets.DROPBOX_REFRESH_TOKEN }}" \
            -d client_id="${{ secrets.DROPBOX_APP_KEY }}" \
            -d client_secret="${{ secrets.DROPBOX_APP_SECRET }}" \
            | jq -r '.access_token')

          if [[ -z "$access_token" || "$access_token" == "null" ]]; then
            echo "Failed to get Dropbox access token"
            exit 1
          fi

          # Mask the token in logs
          echo "::add-mask::$access_token"
          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV

      - name: Set Dropbox target path
        run: |
          if [[ "${GITHUB_REF##*/}" == "master" ]]; then
            echo "TARGET_PATH=/master.pdf" >> $GITHUB_ENV
          else
            echo "TARGET_PATH=/feature.pdf" >> $GITHUB_ENV

      - name: Upload PDF to Dropbox
        run: |
          echo "Uploading resume.pdf to Dropbox at $TARGET_PATH"
          response=$(curl -s -w "%{http_code}" -o /tmp/dropbox_response.json -X POST https://content.dropboxapi.com/2/files/upload \
            --header "Authorization: Bearer $ACCESS_TOKEN" \
            --header "Dropbox-API-Arg: {\"path\":\"$TARGET_PATH\",\"mode\":\"overwrite\",\"autorename\":false}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary @resume.pdf)

          http_code="${response: -3}"  # extract last 3 characters (HTTP code)

          if [[ "$http_code" != "200" ]]; then
            echo "Dropbox upload failed. Response:"
            cat /tmp/dropbox_response.json
            exit 1
          fi

          echo "Dropbox upload succeeded"
