name: Build LaTeX and Upload PDF

on:
  push:
    branches:
      - master
      - 'feature/*'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: resume.tex

      - name: Set Dropbox target path
        id: dropbox-path
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          if [[ "$BRANCH_NAME" == "master" ]]; then
            echo "TARGET_PATH=master.pdf" >> $GITHUB_ENV
          else
            echo "TARGET_PATH=feature.pdf" >> $GITHUB_ENV
          fi

      - name: Upload to Dropbox
        uses: Lewuathe/dropbox-github-action@v1.0.3
        with:
          dropbox-app-key: ${{ secrets.DROPBOX_APP_KEY }}
          dropbox-app-secret: ${{ secrets.DROPBOX_APP_SECRET }}
          dropbox-refresh-token: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          source-path: resume.pdf
          target-path: ${{ env.TARGET_PATH }}
          write-mode: overwrite
